version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: post-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - common-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: post-service-kafka
    depends_on:
      - zookeeper
    networks:
      - common-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped

networks:
  common-network:
    driver: bridge