# Core
server.port: 0
spring:
  application.name: post-service

  # Kafka
  kafka:
    topic: change
    group-id: post
    bootstrap-servers: localhost:9092

  # Datasource
  datasource:
    url: jdbc:h2:mem:post-db
    driverClassName: org.h2.Driver
    username: admin
    password: 12345

  # JPA
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 Database
  h2:
    console:
      enabled: true
      path: /h2

# Logging
logging:
  level:
    root: info

# Service Discovery
eureka:
  instance:
    instance-id: post-service-${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka